name : Environment
on : 
  workflow_dispatch:
    inputs : 
      TARGET_ENVIRONMENT : 
        type : environment
        default : dev
jobs : 
  echo-env : 
      runs-on : ubuntu-latest
      environment : ${{inputs.TARGET_ENVIRONMENT}}
      steps : 
      - run : echo "Dev var is ${{vars.DEV_VAR}}"
      - run : echo "Prod var is ${{vars.PROD_VAR}}"
      - run : echo  "Secrets dev var is ${{secrets.SECRET_DEV}}"
      - run : echo "Secrets prod var is ${{secrets.PROD_SECRET}}"
