name : Github context
env : 
   var : 'workflow'
on : 
   push : 
   workflow_dispatch : 
jobs : 
    echo-context :
      runs-on : ubuntu-latest
      env :
        var : 'job'
      steps : 
        - name : DisplayInformation
          run : |
            echo : "Event name is ${{github.event_name}}"
            echo : "Event is : ${{github.event}}"
            echo : "Ref is ${{github.ref}}"
            echo : "SHA is ${{github.SHA}}"
            echo : "Actor is ${{github.actor}}"
            echo : "Workflow is ${{github.workflow}}"
            echo : "Run Id is ${{github.run_id}}"
            echo : "Run number is ${{github.run_number}}"
            echo : "Env var value : ${{env.var}}"
            echo : "Global variable : ${{vars.MY_VAR1}}"
            echo : "workflow ref : ${{github.workflow_ref}}"
            echo : "triggering actor : ${{github.triggering_actor}}"
            echo : "token : ${{github.token}}"
            echo : "Server url : ${{github.server_url}}"
            echo : "repository owner : ${{github.repository_owner}}"
            echo : "ref type : ${{github.ref_type}}"
            echo : "ref protected  : ${{github.ref_protected}}"
            echo : "job : ${{github.job}}"
            echo : "event path : ${{github.event_path}}"
            echo : "workflow space : ${{github.workspace}}"
          env : 
                var : 'steps'
