name : Github context
env : 
   var : 'workflow'
on : 
   push : 
   workflow_dispatch : 
jobs : 
    echo-context :
      runs-on : ubuntu-latest
      env :
        var : 'job'
      steps : 
        - name : DisplayInformation
          run : |
            echo : "Event name is ${{github.event_name}}"
            echo : "Ref is ${{github.ref}}"
            echo : "SHA is ${{github.SHA}}"
            echo : "Actor is ${{github.actor}}"
            echo : "Workflow is ${{github.workflow}}"
            echo : "Run Id is ${{github.run_id}}"
            echo : "Run number is ${{github.run_number}}"
            echo : "Env var value : ${{env.var}}"
            echo : "Global variable : ${{vars.MY_VAR1}}"
          env : 
                var : 'steps'
