name : Input workflow
run-name : Inputs | debug - ${{inputs.debug}}
on : 
  workflow_dispatch :
     inputs : 
       debug : 
        type : boolean
        default : false
jobs : 
  echo-data : 
    runs-on : ubuntu-latest
    steps : 
        - run : echo "inputs"
