name : needs workflow
on : workflow_dispatch
jobs :
  build : 
    runs-on : ubuntu-latest
    steps : 
      - run : echo "Builds completed"
  test : 
    runs-on : ubuntu-latest
    steps : 
      - run : echo "Test completed"
  deploy : 
    runs-on : ubuntu-latest
    steps : 
      - run : echo "deploy completed"
      
    
