name : Secrets workflow
on : 
  workflow_dispatch :
jobs : 
  echo-secrets : 
    runs-on : ubuntu-latest
    steps : 
      - name : display secrets
        run : |
            echo : "Secrets username : ${{secrets.USER_NAME}}"
            echo : "Secrets PAssword : ${{secrets.PASSWORD}}"
      
